# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: stripesfensky/hugotesting
  open_authoring: true
  base_url: https://sveltia-cms-auth.plushypuppy.workers.dev

publish_mode: editorial_workflow

media_folder: "static/photos"
public_folder: "/photos"

site_url: https://hugo.plushypuppy.club/

show_preview_links: false

slug:
  encoding: "ascii"
  clean_accents: true

editor:
  preview: false

collections:
  - name: "wiki"
    label: "Locations"
    label_singular: "Location"
    icon: "pin_drop"
    folder: "content/wiki"
    filter: { field: "tags", value: ["Locations"] }
    create: true
    extension: md
    format: toml-frontmatter
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true

      - label: "Page Thumbnail"
        name: "pageThumbnailFile"
        widget: "image"
        allow_multiple: false
        choose_url: false

      - label: "Citations"
        name: "citations"
        widget: "list"
        field: { label: "Citation", name: "citation" }

      - label: "Contributors"
        name: "contributors"
        widget: "list"
        field: { label: "Username", name: "contributor" }

      - label: "Body"
        name: "body"
        widget: "markdown"
        editor_components: ['cite', 'wiki-link', 'prompt-button-component']
    
      - label: "Start Date"
        name: "startDate"
        widget: "string"
        hint: "Enter the date in format YYYY-MM-DD. Replace with 0s for unknown year/month/day."
        pattern: ['\d{4}-\d{2}-\d{2}', "Date must be in format YYYY-MM-DD"]

      - label: "End Date"
        name: "endDate"
        widget: "string"
        hint: "Enter the date in format YYYY-MM-DD. Leave empty if unknown or not applicable. Replace with 0s for unknown year/month/day."
        pattern: ['\d{4}-\d{2}-\d{2}', "Date must be in format YYYY-MM-DD"]

      - label: "Concept Unification Date"
        name: "cuDate"
        widget: "string"
        hint: "Enter the date in format YYYY-MM-DD. Leave empty if unknown or not applicable. Replace with 0s for unknown year/month/day."
        pattern: ['\d{4}-\d{2}-\d{2}', "Date must be in format YYYY-MM-DD"]

      - label: "Map Coordinates"
        name: "latitudeLongitude"
        widget: "object"
        fields: 
          - { label: "Latitude", name: "latitude", widget: "number", value_type: "float" }
          - { label: "Longitude", name: "longitude", widget: "number", value_type: "float" }

      - label: "Store Number"
        name: "storeNumber"
        widget: "number"

      - label: "Square Footage"
        name: "sqft"
        widget: "number"
        value_type: "float"

#     - label: "Stage Shows"
#       name: "stages"
#       widget: "list"
#       fields:
#         - { label: "Name", name: "stagename", widget: "string"}
#
#     - label: "Attractions"
#
#     - label: "Animatronics"
#
#     - label: "Franchisees"
#
#     - label: "Remodels"
#
      - label: "Page Tags"
        name: "tags"
        widget: "hidden"
        default: ["Locations"]

#     - label: "Page Categories"